-- MySQL Script generated by MySQL Workbench
-- Sex 28 Set 2018 20:23:32 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Shop00
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Shop00` ;

-- -----------------------------------------------------
-- Schema Shop00
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Shop00` DEFAULT CHARACTER SET utf8 ;
USE `Shop00` ;

-- -----------------------------------------------------
-- Table `Shop00`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shop00`.`Category` (
  `idCategory` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nameCategory` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shop00`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shop00`.`Product` (
  `idProduct` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nameProduct` VARCHAR(45) NULL,
  `priceProduct` VARCHAR(45) NULL,
  `descriptionProduct` VARCHAR(45) NULL,
  `idCategory` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `fk_Product_Category_idx` (`idCategory` ASC),
  CONSTRAINT `fk_Product_Category`
    FOREIGN KEY (`idCategory`)
    REFERENCES `Shop00`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
